spring:
  redis:
    cluster:
      nodes: 192.168.148.128:7000,192.168.148.128:7001,192.168.148.128:7002,192.168.148.129:7003,192.168.148.129:7004,192.168.148.129:7005
#      最大的要重定向的次数（由于集群中数据存储在多个节点所以，在访问数据时需要通过节点进行转发）
      max-redirects: 3
    password:
    pool:
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
    timeout: 5000